[workspace]
preview = ["pixi-build"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
ALF = {path = "."}

[tasks]

[package]
name = "ALF"
version = "0.1.0"

[build-system]
# build-backend = { name = "pixi-build-rattler-build", version = "*" }
build-backend = { name = "pixi-build-cmake", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[host-dependencies]
cmake = ">=3.20, <3.27"      

[build-dependencies]

