[workspace]
preview = ["pixi-build"]
channels = ["conda-forge", "nvidia"]
platforms = ["linux-64"]

[dependencies]
wham = {path = "."}

[tasks]

[package]
name = "wham"
version = "0.1.0"

[build-system]
# build-backend = { name = "pixi-build-rattler-build", version = "*" }
build-backend = { name = "pixi-build-cmake", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[build-dependencies]
cmake = ">=3.20, <3.27"      
gxx_linux-64 = "11.2.*"
cuda = "11.7.*"

[host-dependencies]
openmpi = "4.1.*"
fftw = "3.3.*"
